import { NavigationItem } from "@/types/navigation";

export const FALLBACK_NAV_ITEMS: NavigationItem[] = [
  // Main Navigation Items
  {
    id: "nav-home",
    title: "Home",
    href: "/",
    type: "MAIN",
    order: 1,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },
  {
    id: "nav-services",
    title: "Services",
    href: "/services",
    type: "DROPDOWN",
    order: 2,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },
  {
    id: "nav-projects",
    title: "Projects",
    href: "/projects",
    type: "DROPDOWN",
    order: 3,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },
  {
    id: "nav-about",
    title: "About Us",
    href: "/about",
    type: "DROPDOWN",
    order: 4,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },
  {
    id: "nav-culture",
    title: "People & Culture",
    href: "/culture",
    type: "DROPDOWN",
    order: 5,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },
  {
    id: "nav-components",
    title: "Components",
    href: "/themecheck",
    type: "MAIN",
    order: 6,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },

  // Services Subitems
  {
    id: "nav-services-elections",
    title: "Elections Monitoring",
    href: "/services/elections",
    description: "Comprehensive election monitoring solutions",
    type: "MAIN",
    parentId: "nav-services",
    order: 1,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },
  {
    id: "nav-services-exams",
    title: "Examinations Monitoring",
    href: "/services/examinations",
    description: "Secure examination monitoring systems",
    type: "MAIN",
    parentId: "nav-services",
    order: 2,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },
  {
    id: "nav-services-surveillance",
    title: "Surveillance Systems",
    href: "/services/surveillance",
    description: "Advanced CCTV monitoring solutions",
    type: "MAIN",
    parentId: "nav-services",
    order: 3,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },

  // Projects Subitems
  {
    id: "nav-projects-elections",
    title: "National Elections 2023",
    href: "/projects/elections-2023",
    description: "Our nationwide election monitoring project",
    type: "MAIN",
    parentId: "nav-projects",
    order: 1,
    isActive: true,
    isExternal: false,
    roles: ["USER"],
  },
  // ... add other subitems following the same pattern
];
